### ISSUE TITLE
Crashes on Android Marshmallow

### ISSUE THREAD

**Issue by 12people** [tobihille/SeniorLauncher#3]
I'm using a Nexus 5 with Android Marshmallow (the ROM that came with the phone, not a custom one), and clicking either "Call" or "Images" crashes the launcher.

**Comment by tobihille** [comment]
Thanks for the report, I will try to reproduce it.
Did you used the newest version? Version 1.0 crashed when no contacts were present and "Call" or "Images" were clicked. This should be fixed in Version 1.1 and later.

**Comment by 12people** [comment]
Not sure what version I had before.
Just tried it again (v1.5) and it works.
