### ISSUE TITLE
new translation pt BR

### ISSUE THREAD

**Issue by victante** [tobihille/SeniorLauncher#5]
Hi there! Just discovered your app on F-droid and I'd like to add this translation, as I think it could really help a lot of people in Brazil. Tell me if anything is wrong or missing. 

    * ``Call`` = ``Chamada``
    * ``Images`` = ``Imagens``
    * ``Show all images`` = ``Mostrar todas as imagens``
    * ``Go back`` = ``Voltar``
    * the emergency number for the country, e.g. 112 or 911 (this is important!) = ``192``
    * ``Settings`` (currently not used) = ``Configura&ccedil;&otilde;es``, which should look like ``Configurações``
    * ``Loading, please wait a moment`` = ``Carregando, aguarde um momento``

PS1: I'm not that familiar with programming, so I was not sure what the encoding thing meant, but I supposed it was something related to HTML and then I tried to convert "Configurações" in an online platform). 
PS2: emergency numbers in Brazil aren't quite unified. They work as follows:
190 for a police emergency (ie calls the police)
**192 for a medical emergency (ie calls an ambulance)**
193 for a fire emergency (ie calls the firefighters)
So, I supposed the focus should be the medical emergency, thus added 192 as the emergency number.

**Comment by tobihille** [comment]
Thanks a lot!
I added your translation and it works at least in the Android Emulator so I think everything should be fine. This is the commit: https://github.com/tobihille/SeniorLauncher/commit/2ce22b8336f277fa83d0a969830390bfc8d066e1

Please note: it takes usually a few days until the app is updated in fdroid.
I will close this issue now, if for some strange reason the app is not updating either I will reopen it (I check regularly for updates on fdroid) or you can :-)

Another note: Sorry for the misinformation, "Configurações" is perfectly fine, only special characters like "<" or ">" need to be encoded.
I will correct the file and also clarify that I'm looking for medical emergency number.
