### ISSUE TITLE
New Translation pt-PT

### ISSUE THREAD

**Issue by maverick74** [tobihille/SeniorLauncher#6]
Call - Chamar
Images - Imagens
Show all images - Mostrar todas as imagens
Go back - Voltar

the number which is called in case of a medical emergency: 112

Settings (currently not used) - Opções
Loading, please wait a moment - A carregar, por favor aguarde

**Comment by tobihille** [comment]
I think I will find time to add this this evening. Sorry for not reacting, I didn't noticed the issue (I will change my notification settings right now).

**Comment by maverick74** [comment]
no stress :)

( Off topic: I would like to make a suggestion: maybe, **in some cases**, an option to show an entry to send SMS's would be good. Some seniors do not get along with SMS's, but others do)

**Comment by tobihille** [comment]
That's a good recommendation. I thought about adding a settings screen, maybe this is one of the use cases. I'll open a issue with this suggestion and a few other ideas.

Your translation is added in commit https://github.com/tobihille/SeniorLauncher/commit/a488440f818ce9f185cc6d51d9ad4e4b0b0630b4 and I created a new version so your translation should soon be in fdroid.
Thank you!

**Comment by tobihille** [comment]
Just added #8 which includes your idea. Thank you :-)
